#include "clouds.c"

#define LEVEL_SIZE 1000
char screen[16][101]; // 101 because of the termination character (\0)
short color_screen[16][100];



char debug_layer[16][101];
char debug_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
};


char border_layer[16][101];
char border_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                    ",
    "----------------------------------------------------------------------------------------------------",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "-                                                                                                  -",
    "----------------------------------------------------------------------------------------------------",
};


char mario_layer[16][101];
char mario_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    "                                                                                                    ",
    // "/\\",
    // "MM",
};


char powerups_layer[16][101];
char powerups_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                     S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
};

char obstacles_layer[16][101];
char obstacles_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                           ^                 ^                ^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
};

char ground_layer[16][101];
char ground_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +=========+                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | [] | [] |                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +=========+                                                                           ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               +=======+=======+                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |-------[]------|                                                                        ",
    "                                                                                                          ===== =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +=======+=======+                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    +=========+=====+======+======+==========+                                                          ",
    "                                                                                            ========  ======================   =====                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |---------------[]  |  []----------------|                                                          ",
    "                                                                                      ==============                                  ===================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           +=========+=========+=========+==========+                                                          ",
    "                                                                                 ===================                                                         =======================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +=========+=========+=========+==========+                                                          ",
    "                                                                           =========================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ==================================|--------------[] | [] | []--------------|                                                          ",
    "                                                                        ============================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [][][][][][][][][][][][][][][][][]+=========+=========+=========+==========+                                                          ",
    "====================================================================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ===================================================================================                                                   ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
};


char background_layer[16][101];
char background_layer_init[16][LEVEL_SIZE] = {
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
};


#define NUM_LAYERS 7
enum layers {
    BG_LAYER = 0,
    GROUND_LAYER = 1,
    OBS_LAYER = 2,
    STAR_LAYER = 3,
    MARIO_LAYER = 4,
    BORDER_LAYER = 5,
    DEBUG_LAYER = 6,
};

char (*layers[NUM_LAYERS])[101] = {
    background_layer,
    ground_layer,
    obstacles_layer,
    powerups_layer,
    mario_layer,
    border_layer,
    debug_layer,
};


char (*layer_init[NUM_LAYERS])[LEVEL_SIZE] = { 
    background_layer_init,
    ground_layer_init,
    obstacles_layer_init,
    powerups_layer_init,
    mario_layer_init,
    border_layer_init,
    debug_layer_init,
};

int layer_colors[NUM_LAYERS] = {
    1,   // background
    2,   // ground
    3,   // obstacles
    7,   // powerup/star
    4,   // mario
    5,   // border
    1,   // debug
};


void set_mario_position(int x, int y) {
    if (y < 3) { // set bounds
        y = 3;
    } else if (y > 14) {
        y = 14;
    }
    if (x < 1) {
        x = 1;
    } else if (x > 98) {
        x = 98;
    }

    for (int y = 0; y < 16; y++) {
        for (int x = 0; x < 100; x++) {
            mario_layer[y][x] = ' ';
        }
        mario_layer[y][100] = '\0';
    }

    //placeholder mario shape
    mario_layer[y][x]     = 'M';
    mario_layer[y][x+1]   = 'M';
    mario_layer[y-1][x]   = '/';
    mario_layer[y-1][x+1] = '\\';
}

int scrollX = 0; // how many horizontal units have been scrolled

void shift_row(char *row) {
    for (int x = 0; row[x] != '\0'; x++) {
        row[x] = row[x+1];
    }
}

void update_row(char *row, int i, int y) {
    row[99] = layer_init[i][y][scrollX+99];
}



void scroll_level() {
    //scrolls background, ground, and obstacles layers
    scrollX++;

    for (int i = BG_LAYER; i < MARIO_LAYER; i++) {
        for (int y = 0; y < 16; y++) {
            shift_row(layers[i][y]);
            update_row(layers[i][y], i, y);
        }
    } 
}

short r = 0;
short g = 0;
short b = 0;

void update_invincibility_colors(int timer, int invincTimer) {
    int hue = (timer << 3) % 360;
    float sat = 1.0f;
    float val = 0.8f;

    if (invincTimer < 15) {
        if ((invincTimer % 6) <= 2) {
            val = 0.6f;
            sat = 0.2f;
        }
    }

    hsv_to_rgb(hue, sat, val, &r, &g, &b);

    //update mario layer and border layer
    init_pair(4, COLOR256(r, g, b), COLOR_BLACK);
    init_pair(5, COLOR256(r, g, b), COLOR256(r, g, b));
}



void set_up_colors() {
    start_color();
    init_pair(1, COLOR256(4, 5, 5), COLOR_BLACK);   // background layer
    init_pair(2, COLOR_GREEN, COLOR_BLACK);  // ground layer
    init_pair(3, COLOR256(5, 2, 0), COLOR_BLACK);  // obstacles layer
    init_pair(4, COLOR_RED, COLOR_BLACK);  // mario layer
    init_pair(5, COLOR256(0, 0, 1), COLOR256(0, 0, 1));  // border layer
    init_pair(6, COLOR_BLACK, COLOR_BLACK);  // EMPTY layer
    init_pair(7, COLOR_YELLOW, COLOR_BLACK);  // Star/Powerup layer
}


void add_cloud(int x, int y, int cloud) {
    for (int yCord = 0; yCord < CLOUD_HEIGHT; yCord++) {
        for (int xCord = 0; clouds[cloud][yCord][xCord] != '\0'; xCord++) {
            if (clouds[cloud][yCord][xCord] != ' ') {
                background_layer_init[y+yCord][x+xCord] = clouds[cloud][yCord][xCord];
            }
        }
    }
}


void add_background_elements() {
    for (int i = 0; i < (LEVEL_SIZE/20) - 3; i++) {
        int height = 1 + (rand() % 10);
        int xOffset = rand() % 10;
        int cloud = rand() % NUM_CLOUDS;
        add_cloud((i*20) + xOffset, height, cloud);
    }
}

void init_layers() {
    add_background_elements();
    for (int i = 0; i < NUM_LAYERS; i++) {
        for (int y = 0; y < 16; y++) {
            strncpy(layers[i][y], layer_init[i][y], 100);
            layers[i][y][100] = '\0';  // ensure null-terminated
        }
    }
}



void assemble_layers() {
    //first: clear screen matrix
    for (int y = 0; y < 16; y++) {
        for (int x = 0; x < 100; x++) {
            screen[y][x] = ' ';
            color_screen[y][x] = 6;
        }
        screen[y][100] = '\0';
    }

    //then: apply layers
    for (int i = 0; i < NUM_LAYERS; i++) {
        for (int y = 0; y < 16; y++) {
            for (int x = 0; layers[i][y][x] != '\0' && x < 100; x++) {
                if (layers[i][y][x] != ' ') {
                    screen[y][x] = layers[i][y][x];
                    color_screen[y][x] = layer_colors[i];
                }
            }
        }
    }
}

void render_screen() {
    for (int y = 0; y < 16; y++) {
        for (int x = 0; x < 100; x++) {
            attron(COLOR_PAIR(color_screen[y][x]));
            mvaddch(y, x, screen[y][x]);
            attroff(COLOR_PAIR(color_screen[y][x]));
        }
    }
    refresh();
}